node.id=1
node.port=9282
broker.port=9182
broker.timeout=1000
peers=2:localhost:9285,3:localhost:9287
raft.indexer.path=/tmp/mini-kafka/raft/index/currentIndex
raft.indexer.size=2000000
raft.logger.path=/tmp/mini-kafka/raft/logger/currentLog
scheduled.triggerElection.lowerBound=150
scheduled.triggerElection.upperBound=300
scheduled.heartbeat.fixedRate=50